// End-to-end smoke: PDP → bag → checkout → order page → admin shows order. Usage: node scripts/e2e.mjs
import { chromium } from "playwright-core";
const base = `http://localhost:${process.env.PORT || 3100}`;
const out = process.env.OUT || ".";
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => m.type() === "error" && errors.push(m.text()));
const step = (s) => console.log("•", s);

await page.goto(`${base}/products/aurelia-diamond-studs`, { waitUntil: "networkidle" });
step("PDP loaded");
await page.getByRole("radio", { name: "Rose Gold" }).first().click();
await page.getByRole("button", { name: "Add to bag" }).first().click();
await page.getByRole("dialog", { name: "Shopping bag" }).waitFor();
step("Added studs; drawer open");
await page.screenshot({ path: `${out}/e2e-drawer.png` });
await page.goto(`${base}/products/elan-solitaire-ring`, { waitUntil: "networkidle" });
await page.getByRole("button", { name: "Add to bag" }).first().click();
await page.getByText("Please choose a size").waitFor();
step("Size validation shown");
await page.getByRole("radio", { name: "14", exact: true }).click();
await page.getByRole("button", { name: "Add to bag" }).first().click();
await page.getByRole("dialog", { name: "Shopping bag" }).waitFor();
step("Added solitaire size 14");
await page.goto(`${base}/checkout`, { waitUntil: "networkidle" });
await page.getByLabel("Email").fill("test.buyer@example.com");
await page.getByLabel(/Mobile/).fill("+91 98100 00000");
await page.getByRole("button", { name: "Continue to delivery" }).click();
await page.getByLabel("Full name").fill("Test Buyer");
await page.getByLabel("Address", { exact: true }).fill("12 Aralias, Golf Course Road");
await page.getByLabel("PIN code").fill("122002");
await page.getByLabel("City").fill("Gurugram");
await page.getByLabel("State").fill("Haryana");
await page.getByRole("button", { name: "Continue to payment" }).click();
await page.getByLabel("Promo code").fill("DIWALI26");
await page.getByRole("button", { name: "Apply" }).click();
await page.getByText(/DIWALI26:/).waitFor();
step("Coupon applied");
await page.screenshot({ path: `${out}/e2e-checkout.png`, fullPage: true });
await page.getByRole("button", { name: /^Pay / }).click();
await page.waitForURL(/\/order\/SLN-/, { timeout: 30000 });
const number = page.url().split("/order/")[1].split("?")[0];
step(`Order placed ${number}`);
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/e2e-order.png`, fullPage: false });
await page.goto(`${base}/admin/orders`, { waitUntil: "networkidle" });
const found = await page.getByText(number).count();
step(`Admin lists order: ${found > 0}`);
await page.getByText(number).first().click();
await page.waitForURL(/admin\/orders\/ord-/);
await page.getByRole("button", { name: "Mark quality check" }).click();
await page.getByText(/Status updated/).waitFor();
step("Admin status updated");
await page.goto(`${base}/admin/audit`, { waitUntil: "networkidle" });
step(`Audit has status change: ${(await page.getByText("order.status_changed").count()) > 0}`);
console.log("errors:", errors.slice(0, 5));
await browser.close();
