import { chromium } from "playwright-core";
const S = process.env.OUT;
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, args: ["--use-angle=swiftshader","--enable-unsafe-swiftshader","--use-fake-ui-for-media-stream","--use-fake-device-for-media-stream"] });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, permissions: ["camera"] });
const p = await ctx.newPage();
const errs = []; p.on("pageerror", e => errs.push(e.message));
await p.goto("http://localhost:3100/products/elan-solitaire-ring", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /Find your size/ }).click();
await p.getByRole("tab", { name: "Measure a ring" }).click();
await p.getByPlaceholder("e.g. 16.5").fill("17");
await p.getByRole("button", { name: "Use this size" }).click();
console.log("size selected:", await p.getByRole("radio", { name: "14", exact: true }).getAttribute("aria-checked"), await p.locator('[role=radio][aria-checked=true]').allInnerTexts());
await p.getByRole("button", { name: /Try on/ }).click();
await p.getByRole("button", { name: /Open camera/ }).click();
await p.waitForTimeout(2500);
await p.screenshot({ path: `${S}/tryon.png` });
await p.getByRole("button", { name: "Capture" }).click();
await p.waitForTimeout(1000);
console.log("captured:", await p.getByText("Captured").count());
await p.keyboard.press("Escape");
await p.goto("http://localhost:3100/configure", { waitUntil: "networkidle" });
for (let i = 0; i < 5; i++) await p.getByRole("button", { name: "Continue" }).click();
await p.getByRole("radio", { name: "12", exact: true }).click();
await p.getByRole("button", { name: "Continue" }).click();
await p.getByRole("button", { name: "Continue" }).click();
await p.getByRole("button", { name: "Add to bag" }).click();
await p.getByRole("dialog", { name: "Shopping bag" }).waitFor();
await p.goto("http://localhost:3100/checkout", { waitUntil: "networkidle" });
await p.getByLabel("Email").fill("b@example.com"); await p.getByLabel(/Mobile/).fill("+91 98100 00001");
await p.getByRole("button", { name: "Continue to delivery" }).click();
await p.getByRole("radio", { name: /Collect from a boutique/ }).click();
await p.getByLabel("Full name").fill("Bespoke Buyer");
await p.getByRole("button", { name: "Continue to payment" }).click();
await p.getByRole("button", { name: /^Pay / }).click();
await p.waitForURL(/\/order\//, { timeout: 30000 });
await p.waitForTimeout(1200);
await p.screenshot({ path: `${S}/bespoke-order.png` });
console.log("bespoke order ok", p.url(), errs);
await b.close();
